# backend/routers/pipeline.py
# POST /pipeline — Full audio-to-report pipeline
#
# Step-by-step orchestration:
#   1. Decode base64 audio → save to temp/REQ-XXX_raw.wav
#   2. Denoise → temp/REQ-XXX_clean.wav
#   3. Transcribe (Whisper) → transcript string
#   4. Retrieve RAG chunks (LlamaIndex) → top-k chunks + is_vague flag
#   4b. If is_vague: expand with LLM hypotheses → retry retrieval
#   5. RAG triage (LLaMA 3.2 3B) → multi-situation JSON
#   6. Annotate each situation's materials with inventory availability
#   7. Store full request, return PipelineResponse

import uuid
from datetime import datetime

from fastapi import APIRouter, HTTPException

from schemas import PipelineRequest, PipelineResponse
from agents import (
    denoise,
    transcribe,
    retrieve,
    resolve_and_retrieve,
    run_rag_triage,
    annotate_situations,
)
from core.priority_queue import priority_queue
from core.request_store import request_store
from utils.audio_utils import save_base64_wav, get_clean_path, cleanup_temp
from utils.logger import log_handoff

# Create router instance for pipeline endpoints
router = APIRouter()

# LLM instance — loaded lazily on first POST /pipeline call
# This prevents loading the model during startup, keeping health checks fast
_llm_instance = None


def _get_llm():
    """
    Lazily load the LLaMA model on first request.
    
    Returns:
        Llama: Initialized LLaMA model instance
    """
    global _llm_instance
    if _llm_instance is None:
        # Import here to avoid circular imports and keep startup fast
        from llama_cpp import Llama
        from config import LLAMA_MODEL_PATH, LLM_CONTEXT_SIZE

        # Initialize LLaMA model with CPU-only inference
        _llm_instance = Llama(
            model_path=LLAMA_MODEL_PATH, 
            n_ctx=LLM_CONTEXT_SIZE,  # Context window size
            verbose=False  # Reduce console output
        )
    return _llm_instance


@router.post("/pipeline", response_model=PipelineResponse)
async def run_pipeline(pipeline_request: PipelineRequest):
    """
    Execute the complete audio-to-report pipeline.
    
    This endpoint orchestrates all agents in sequence:
    
    Flow:
    ┌────────────┐    ┌──────────┐    ┌─────────────┐
    │Audio Input │───▶│ Denoiser │───▶│ Transcriber │
    └────────────┘    └──────────┘    └─────────────┘
                                              │
                                              ▼
    ┌────────────┐    ┌─────────────┐    ┌──────────┐
    │   Store    │◀───│   Triage    │◀───│ Retrieval│
    └────────────┘    └─────────────┘    └──────────┘
                           │
                           ▼
                    ┌─────────────┐
                    │  Inventory  │
                    │  Annotation │
                    └─────────────┘
    
    Args:
        pipeline_request: PipelineRequest with:
            - audio_b64: Base64-encoded WAV audio
        
    Returns:
        PipelineResponse containing:
            - request_id: Unique identifier
            - transcript: Transcribed text
            - is_vague: Whether retrieval was uncertain
            - situations: List of identified emergency situations
            - handoff_logs: Trace of agent-to-agent handoffs
    
    Raises:
        HTTPException 500: If any pipeline step fails
    """
    # STEP 0: Generate unique request ID (e.g., "REQ-ABC123")
    request_id = f"REQ-{uuid.uuid4().hex[:6].upper()}"
    
    # Initialize empty handoff log for this request
    handoff_logs: list[dict] = []

    # STEP 1 — Decode and save raw audio
    # Convert base64 to WAV file and save to temp directory
    raw_audio_path = save_base64_wav(pipeline_request.audio_b64, request_id)
    
    # Get path for cleaned audio (to be generated by denoiser)
    cleaned_audio_path = get_clean_path(request_id)

    # STEP 2 — Audio Denoising
    # Log handoff from user input to denoiser agent
    log_handoff(
        from_agent="AUDIO_INPUT", 
        to_agent="DENOISER", 
        reason="start pipeline", 
        payload={"request_id": request_id}
    )
    
    # Apply noise reduction to improve transcription accuracy
    denoise(raw_audio_path, cleaned_audio_path)

    # STEP 3 — Speech Transcription
    # Log handoff from denoiser to intake agent
    log_handoff(
        from_agent="DENOISER", 
        to_agent="INTAKE_AGENT", 
        reason="audio cleaned", 
        payload={"clean_path": cleaned_audio_path}
    )
    
    # Convert speech to text using Whisper
    transcript_text = transcribe(cleaned_audio_path)

    # STEP 4 — Initial Retrieval (RAG)
    # Log handoff from intake to retrieval agent
    log_handoff(
        from_agent="INTAKE_AGENT", 
        to_agent="RETRIEVAL_AGENT", 
        reason="transcribed", 
        payload={"transcript": transcript_text}
    )
    
    # Retrieve relevant protocol chunks from vector store
    retrieval_result = retrieve(transcript_text)
    relevant_chunks = retrieval_result["chunks"]

    # STEP 4b — Vagueness Resolution (if needed)
    # Check if retrieval confidence was too low
    if retrieval_result["is_vague"]:
        # Log handoff to vagueness agent for clarification
        log_handoff(
            from_agent="RETRIEVAL_AGENT",
            to_agent="VAGUENESS_AGENT",
            reason=f"top_score={retrieval_result['top_score']:.2f} < threshold=0.8",
            payload={
                "transcript": transcript_text, 
                "top_score": retrieval_result["top_score"]
            },
        )
        
        # Record this step in handoff logs for response
        handoff_logs.append(
            {
                "step": "vagueness_resolved",
                "reason": f"low confidence ({retrieval_result['top_score']:.2f})",
            }
        )
        
        # Use LLM to generate hypotheses and retry retrieval
        relevant_chunks = resolve_and_retrieve(
            transcript_text, 
            _get_llm(),  # Lazy load LLM here
            retrieve
        )

    # STEP 5 — RAG Triage (Situation Identification)
    # Log handoff from retrieval to triage agent
    log_handoff(
        from_agent="RETRIEVAL_AGENT",
        to_agent="RAG_TRIAGE_AGENT",
        reason="chunks ready",
        payload={"chunk_count": len(relevant_chunks)},
    )
    
    # Identify potential emergency situations using LLM
    identified_situations = run_rag_triage(
        transcript_text, 
        relevant_chunks, 
        _get_llm()
    )

    # STEP 6 — Inventory Annotation
    # Log handoff from triage to logistics agent
    log_handoff(
        from_agent="RAG_TRIAGE_AGENT",
        to_agent="LOGISTICS_AGENT",
        reason="situations ready",
        payload={"count": len(identified_situations)},
    )
    
    # Check inventory availability for each situation's materials
    situations_with_inventory = annotate_situations(identified_situations)

    # STEP 7 — Store Request (Pending Approval)
    # Create complete request record
    full_request = {
        "request_id": request_id,
        "time_of_request": datetime.now().isoformat(),
        "transcript": transcript_text,
        "is_vague": retrieval_result["is_vague"],
        "situations": situations_with_inventory,
        "status": "PENDING",  # Awaiting HITL approval
        # Calculate initial priority (highest among all situations)
        "heap_key": max(
            (s["heap_key"] for s in situations_with_inventory), 
            default=0
        ),
        "escalation_stage": 0,  # No escalations yet
        "handoff_logs": handoff_logs,
    }
    
    # Store in request registry
    request_store.add(full_request)
    
    # Note: Not pushed to priority_queue yet — waits for POST /approve
    # This is where HITL (Human-in-the-Loop) approval happens

    # STEP 8 — Cleanup temporary audio files
    cleanup_temp(request_id)

    # STEP 9 — Return pipeline results to client
    return PipelineResponse(
        request_id=request_id,
        transcript=transcript_text,
        is_vague=retrieval_result["is_vague"],
        situations=situations_with_inventory,
        handoff_logs=handoff_logs,
    )